# Generated by Django 5.2.8 on 2025-11-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(default=1, verbose_name='Contenido del Comentario'),
            preserve_default=False,
        ),
    ]
