# Generated by Django 4.2.7 on 2025-11-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_alter_sensor_categoria'),
        ('comentarios', '0002_comentario_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='id_sensor',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor', verbose_name='Sensor'),
        ),
    ]
