# Generated by Django 4.2.7 on 2025-12-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_alter_sensor_categoria'),
        ('comentarios', '0005_alter_comentario_id_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_sensor',
            field=models.ForeignKey(blank=True, db_column='sensor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor', verbose_name='Sensor'),
        ),
    ]
