# Generated by Django 4.2.7 on 2025-12-01 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensores', '0003_alter_sensor_categoria'),
        ('comentarios', '0006_alter_comentario_id_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id_user',
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_sensor',
            field=models.ForeignKey(db_column='sensor_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor', verbose_name='Sensor'),
            preserve_default=False,
        ),
    ]
