services:
  # Django conectado a MySQL local
  django-app:
    build: ./catalog-service
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      JWT_SECRET: mi-clave-secreta-jwt-muy-segura-para-ecommerce
      JWT_EXPIRE: 3600
      REFRESH_TOKEN_EXPIRE: 604800
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./media:/app/media
      - ./catalog-service/staticfiles:/app/staticfiles

  # Payment Service conectado a MySQL local + Django
  payment-service:
    build: ./payment-service
    ports:
      - "8085:8080" # Puerto externo 8085 -> Puerto interno 8080 (Spring Boot)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      JWT_SECRET: mi-clave-secreta-jwt-muy-segura-para-ecommerce
      DJANGO_SERVICE_URL: http://django-app:8000/api
      NOTIFICATION_BASE_URL: http://django-app:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - django-app

  # Servicio de Autenticación (PHP) conectado a MySQL local
  auth-service:
    build: ./auth-service
    ports:
      - "8081:80"
    environment:
      DB_HOST: host.docker.internal
      DB_NAME: auth_db
      DB_USER: root
      DB_PASS: ""
      DB_PORT: 3306
      JWT_SECRET: mi-clave-secreta-jwt-muy-segura-para-ecommerce
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./auth-service/logs:/var/www/html/logs
