#!/bin/bash
echo "=== Verificando JWT_SECRET en todos los servicios ==="
echo ""
echo "Auth Service (.env):"
grep JWT_SECRET auth-service/.env || echo "❌ No encontrado"
echo ""
echo "Catalog Service (settings.py):"
grep JWT_SECRET_KEY catalog-service/settings.py || echo "❌ No encontrado"
echo ""
echo "Payment Service (application.yml):"
grep "secret:" payment-service/src/main/resources/application.yml || echo "❌ No encontrado"
echo ""
echo "=== Verificación completa ===" 
