# Generated by Django 4.2.7 on 2025-11-29 17:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único que el usuario ingresará (ej: VERANO2025)', max_length=50, unique=True, verbose_name='Código del Cupón')),
                ('descripcion', models.CharField(help_text='Descripción breve del cupón', max_length=200, verbose_name='Descripción')),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Fijo')], max_length=20, verbose_name='Tipo de Descuento')),
                ('valor_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje (1-100) o monto fijo en PEN', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor del Descuento')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto mínimo requerido para aplicar el cupón', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Mínimo de Compra')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora desde la cual el cupón es válido', verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora hasta la cual el cupón es válido', verbose_name='Fecha de Fin')),
                ('usos_maximos', models.IntegerField(blank=True, help_text='Número máximo total de veces que se puede usar. Dejar vacío para ilimitado', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Usos Máximos Totales')),
                ('usos_actuales', models.IntegerField(default=0, help_text='Contador de cuántas veces se ha usado', verbose_name='Usos Actuales')),
                ('usos_por_usuario', models.IntegerField(default=1, help_text='Número máximo de veces que un usuario puede usar este cupón', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Usos Máximos por Usuario')),
                ('activo', models.BooleanField(default=True, help_text='Si el cupón está activo o desactivado', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cupón de Descuento',
                'verbose_name_plural': 'Cupones de Descuento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.BigIntegerField(help_text='ID del usuario que usó el cupón', verbose_name='ID de Usuario')),
                ('order_id', models.BigIntegerField(blank=True, help_text='ID de la orden en la que se usó el cupón', null=True, verbose_name='ID de Orden')),
                ('monto_descuento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Descuento Aplicado')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Original (antes del descuento)')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='cupones.cupon', verbose_name='Cupón')),
            ],
            options={
                'verbose_name': 'Uso de Cupón',
                'verbose_name_plural': 'Historial de Uso de Cupones',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.AddIndex(
            model_name='cupon',
            index=models.Index(fields=['codigo'], name='cupones_cup_codigo_224e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='cupon',
            index=models.Index(fields=['activo'], name='cupones_cup_activo_669720_idx'),
        ),
        migrations.AddIndex(
            model_name='usocupon',
            index=models.Index(fields=['cupon', 'usuario_id'], name='cupones_uso_cupon_i_d7991b_idx'),
        ),
        migrations.AddIndex(
            model_name='usocupon',
            index=models.Index(fields=['order_id'], name='cupones_uso_order_i_9d213a_idx'),
        ),
    ]
