# Generated by Django 4.2.7 on 2025-11-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Sensor')),
                ('tipo', models.CharField(choices=[('humedad', 'Sensor de Humedad'), ('temperatura', 'Sensor de Temperatura'), ('ph', 'Sensor de pH'), ('luz', 'Sensor de Luz'), ('nutrientes', 'Sensor de Nutrientes'), ('co2', 'Sensor de CO2')], max_length=20, verbose_name='Tipo de Sensor')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('rango_medicion', models.CharField(max_length=100, verbose_name='Rango de Medición')),
                ('precision', models.CharField(max_length=50, verbose_name='Precisión')),
                ('alimentacion', models.CharField(max_length=50, verbose_name='Alimentación')),
                ('protocolo_comunicacion', models.CharField(max_length=50, verbose_name='Protocolo de Comunicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='sensores/', verbose_name='Imagen del Sensor')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
