# Generated by Django 5.2.8 on 2025-11-22 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='tipo',
        ),
        migrations.AddField(
            model_name='sensor',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoría'),
            preserve_default=False,
        ),
    ]
