# Generated by Django 4.2.7 on 2025-11-29 15:07

from django.db import migrations, models
import django.db.models.deletion
# Generated by Django 5.2.8 on 2025-11-24 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('sensores', '0002_remove_sensor_tipo_sensor_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='categorias.categoria', verbose_name='Categoría'),
        ),
    ]
