# Generated by Django 5.2.8 on 2025-11-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_alter_sensor_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Sensor'),
        ),
    ]
