server:
  port: 8080

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ecommerce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: TU_EMAIL
    password: TU_PASSWORD_APP
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mi-clave-secreta-jwt-muy-segura-para-ecommerce
  expiration: 3600000


### ✨ ESTA ES LA CLAVE
catalog:
  base-url: http://catalog-service:8000


django:
  service:
    url: http://django-app:8000/api


notification:
  base-url: http://localhost:8000
  retry-attempts: 3
  retry-backoff-ms: 500

logging:
  level:
    com.example.payment_service: DEBUG
