# Generated by Django 5.2.8 on 2025-11-22 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Favorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID Usuario')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca Favorita')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Favorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID Usuario')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoría Favorita')),
            ],
        ),
    ]
