# Generated by Django 5.2.7 on 2025-10-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('category', models.CharField(choices=[('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Action', 'Action')], max_length=10)),
            ],
        ),
    ]
