# Generated by Django 5.2.5 on 2025-10-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_delete_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
