# Generated by Django 5.2.8 on 2025-11-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_add_purchase_history_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(default='Corrección de migración', help_text='Motivo del movimiento de inventario', max_length=100, verbose_name='Motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='descripcion',
            field=models.CharField(help_text='Descripción del movimiento', max_length=200, verbose_name='Descripción'),
        ),
    ]
