# Generated by Django 4.2.7 on 2025-11-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_producto_to_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, help_text='Motivo del movimiento de inventario', max_length=100, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='descripcion',
            field=models.CharField(help_text='Descripción del movimiento', max_length=200, verbose_name='Descripción'),
        ),
    ]
