# Generated by Django 4.2.7 on 2025-11-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_alter_sensor_categoria'),
        ('inventario', '0004_movimientoinventario_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_producto_rel', to='sensores.sensor', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_sensor_rel', to='sensores.sensor', verbose_name='Sensor'),
        ),
    ]
