# Generated by Django 4.2.7 on 2025-11-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_alter_sensor_categoria'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_item_producto_rel', to='sensores.sensor', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='itemorden',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_item_sensor_rel', to='sensores.sensor', verbose_name='Sensor'),
        ),
    ]
