# Generated by Django 4.2.7 on 2025-11-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_itemorden_nombre_producto_orden_payment_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorden',
            name='nombre_producto',
        ),
    ]
