# Generated by Django 5.2.8 on 2025-11-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['orden', '-fecha_creacion'], 'verbose_name': 'Banner Promocional', 'verbose_name_plural': 'Banners Promocionales'},
        ),
        migrations.AddField(
            model_name='banner',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='banner',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace (Opcional)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden de aparición'),
        ),
    ]
